spring:
  datasource:
    url: jdbc:mysql://223.93.170.82:23606/sys-qctest
    username: root
    password: lantone
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true

mybatis-plus:
  mapper-locations: classpath*:mapper/changx/*.xml,classpath*:mapper/orglib/*.xml
  type-aliases-package: com.nuena.changx.entity,com.nuena.orglib.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger.title: 数据分析服务
swagger.des: 数据分析相关业务
swagger.version: 0.0.1-SNAPSHOT