spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      lantone:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://223.93.170.82:23606/sys-qctest
        username: root
        password: lantone
        initial-size: 8
        min-idle: 1
        max-active: 20
        max-wait: 60000
        time-between-eviction-runsMillis: 60000
        min-evictable-idle-timeMillis: 300000
        validation-query: select 'x' FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 20
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        use-global-data-source-stat: true
      huazo:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@192.168.0.97:1521:orcl
        username: ETRACKMRQC
        password: ETRACKMRQC
        initial-size: 8
        min-idle: 1
        max-active: 20
        max-wait: 60000
        time-between-eviction-runsMillis: 60000
        min-evictable-idle-timeMillis: 300000
        validation-query: select 'x' FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 20
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        use-global-data-source-stat: true

mybatis-plus:
  mapper-locations: classpath*:mapper/huazo/*.xml,classpath*:mapper/lantone/*.xml
  type-aliases-package: com.nuena.huazo.entity,com.nuena.lantone.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger.title: 数据分析服务
swagger.des: 数据分析相关业务
swagger.version: 0.0.1-SNAPSHOT