spring:
  datasource:
    url: jdbc:mysql://localhost:3306/painsect
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true

mybatis-plus:
  mapper-locations: classpath*:mapper/bkmy/*.xml
  type-aliases-package: com.nuena.bkmy.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger.title: 爬虫服务
swagger.des: 爬虫相关业务
swagger.version: 0.0.1-SNAPSHOT

##疾病条目爬取是否完成
disease.entry.insect.finished: true
##疾病html爬取是否完成
disease.html.insect.finished: true
##科室爬取是否完成
dept.insect.finished: true
##症状条目爬取是否完成
symptom.entry.insect.finished: true
##症状html爬取是否完成
symptom.html.insect.finished: true
##检查条目爬取是否完成
examine.entry.insect.finished: true
##检查html爬取是否完成
examine.html.insect.finished: true
##治疗条目爬取是否完成
treat.entry.insect.finished: false
##治疗html爬取是否完成
treat.html.insect.finished: false
##预防条目爬取是否完成
prevent.entry.insect.finished: false
##预防html爬取是否完成
prevent.html.insect.finished: false
##护理条目爬取是否完成
nurse.entry.insect.finished: false
##护理html爬取是否完成
nurse.html.insect.finished: false
##中医条目爬取是否完成
chinmed.entry.insect.finished: false
##中医html爬取是否完成
chinmed.html.insect.finished: false